Repository h22k/mng-kargo-php-sdk, pull requests merged in 2024-05, with the labels that each got.

#1 development
  .github/workflows/php.yml
  .php-cs-fixer.dist.php
  README.md
  composer.json
  composer.lock
  src/Contract/ClientInterface.php
  src/Contract/HttpValue.php
  src/Converter.php
  src/Enum/ContentType.php
  src/Enum/HttpMethod.php
  src/Exception/InvalidJsonException.php
  src/Exception/InvalidObjectException.php
  src/Factory.php
  src/Http/Payload.php
  src/Http/ValueObject/AbstractValueObject.php
  src/Http/ValueObject/Body.php
  src/Http/ValueObject/Header.php
  src/Http/ValueObject/QueryParam.php
  src/MngClient.php
  src/MngClientRequestOption.php
  src/Model/Contract/Model.php
  src/Model/Response/CbsInfo/City.php
  src/Model/Response/CbsInfo/CityResponse.php
  src/Model/Response/CbsInfo/Distinct.php
  src/Model/Response/CbsInfo/DistrictResponse.php
  src/Model/Response/CbsInfo/Object/City.php
  src/Model/Response/CbsInfo/Object/District.php
  src/Model/Response/MngResponse.php
  src/Resource/BarcodeCommand.php
  src/Resource/CbsInfo.php
  src/Service/BarcodeService.php
  src/Service/LoginService.php
  src/Service/ResponseTransformerService.php
  tests/Feature/ArchTest.php
  tests/MngTestCase.php
  tests/TestCase.php
  tests/Unit/FactoryTest.php
  tests/Unit/MngClientRequestOptionTest.php
  tests/Unit/MngClientTest.php
  tests/Unit/MngTest.php
  tests/Unit/Resource/CbsInfoTest.php
  tests/Unit/Service/LoginServiceTest.php
Labels: bug, enhancement

#2 Document
  .gitignore
  composer.json
  phpcs.xml
  src/Enum/HttpMethod.php
  src/Factory.php
  src/Http/Payload.php
  src/Mng.php
  src/MngClient.php
  src/MngClientRequestOption.php
  src/Model/Response/CbsInfo/CityResponse.php
  src/Model/Response/CbsInfo/DistrictResponse.php
  src/Resource/CbsInfo.php
  src/Service/LoginService.php
  src/Service/ResponseTransformerService.php
Labels: documentation

#4 feat: added new test cases with the purpose of reaching min 90 coverage
  Makefile
  src/Http/Payload.php
  src/Model/Response/CbsInfo/CityResponse.php
  src/Model/Response/CbsInfo/DistrictResponse.php
  src/Resource/CbsInfo.php
  src/Service/ResponseTransformerService.php
  tests/Unit/Exception/InvalidJsonExceptionTest.php
  tests/Unit/Model/Response/CbsInfo/CityResponseTest.php
  tests/Unit/Model/Response/CbsInfo/DistrictResponseTest.php
  tests/Unit/Model/Response/MngResponseTestCase.php
  tests/Unit/Resource/CbsInfoTest.php
  tests/Unit/Service/ResponseTransformerServiceTest.php
Labels: enhancement

#5 Barcode Resource
  .gitignore
  src/Exception/InvalidObjectException.php
  src/Http/ValueObject/AbstractValueObject.php
  src/Mng.php
  src/MngClient.php
  src/Model/Body/BarcodeCommand/CancelShipmentBody.php
  src/Model/Body/BarcodeCommand/CreateBarcodeBody.php
  src/Model/Body/BarcodeCommand/Trait/HasOrderPieceList.php
  src/Model/Body/BarcodeCommand/UpdateShipmentBody.php
  src/Model/Contract/Arrayable.php
  src/Model/Object/Barcode.php
  src/Model/Object/City.php
  src/Model/Object/District.php
  src/Model/Object/OrderPiece.php
  src/Model/Response/BarcodeCommand/CreateBarcodeResponse.php
  src/Model/Response/CbsInfo/CityResponse.php
  src/Model/Response/CbsInfo/DistrictResponse.php
  src/Model/Response/EmptyResponse.php
  src/Resource/BarcodeCommand.php
  src/Resource/CbsInfo.php
  src/Service/ResponseTransformerService.php
  tests/Unit/MngTest.php
  tests/Unit/Model/Body/BarcodeCommand/CancelShipmentBodyTest.php
  tests/Unit/Model/Body/BarcodeCommand/CreateBarcodeBodyTest.php
  tests/Unit/Model/Body/BarcodeCommand/UpdateShipmentBodyTest.php
  tests/Unit/Model/Response/BarcodeCommand/CreateBarcodeResponseTest.php
  tests/Unit/Model/Response/CbsInfo/CityResponseTest.php
  tests/Unit/Model/Response/CbsInfo/DistrictResponseTest.php
  tests/Unit/Model/Response/EmptyResponseTest.php
  tests/Unit/Resource/BarcodeCommandTest.php
  tests/Unit/Resource/CbsInfoTest.php
Labels: enhancement, good first issue
